image: barichello/godot-ci:3.2.3

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/

stages:
  - build
  - test
  - deploy

variables:
  EXPORT_NAME: hse-godot

linux.build:
  stage: export
  script:
    - mkdir -v -p build/linux
    - cd $EXPORT_NAME
    - godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/linux

linux.test:
  stage: export
  script:
    - mkdir -v -p test/linux
    - cd build/test
    - cd $EXPORT_NAME
    - godot -v --export "Linux/X11" ../test/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - test/linux

linux.deploy:
  stage: export
  script:
    - mkdir -v -p
    - cd deploy/linux
    - cd $EXPORT_NAME
    - godot -v --export "Linux/X11" ../deploy/linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - deploy/linux


