services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
    volumes:
      - '/Users/yawsampenebuadu/gitlab/config:/etc/gitlab'
      - '/Users/yawsampenebuadu/gitlab/logs:/var/log/gitlab'
      - '/Users/yawsampenebuadu/gitlab/data:/var/opt/gitlab'
#      - '$GITLAB_HOME/config:/etc/gitlab'
#      - '$GITLAB_HOME/logs:/var/log/gitlab'
#      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab-ee

  runner:
    image: 'gitlab/gitlab-runner:latest'
    volumes:
      - "/Users/Shared/gitlab-runner/config:/etc/gitlab-runner"
      - "/var/run/docker.sock:/var/run/docker.sock"
#    volumes:
#      - '/srv/gitlab-runner/config:/Users/yawsampenebuadu/Documents/MSC Systems & Software Engineering/Dev Ops Course/ci practice/gitlab'
#      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
   gitlab-ee:
    name: 'gitlab-hse'
    driver: 'bridge'      
